- hosts: master1
  become: yes
  become_user: root
  tasks:
  - name: Wait for api
    uri: 
       url: "http://master1:8443/api"
       validate_certs: False
    register: result
    until: ('status' in result) and (result.status == 200 or result.status == 401)
    retries: 60000
    delay: 10
    changed_when: false
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Get server url
    shell: "oc whoami --show-server"
    register: api_url
  - local_action: copy content="{{ api_url.stdout }}" dest=/root/api_host.txt
- hosts: master1
  become: yes
  become_user: root
  tasks:
  - name: Create the ovn scc account
    shell: oc create serviceaccount ovn
    ignore_errors: yes
  - name: Add the cluster role
    shell: oc adm policy add-cluster-role-to-user cluster-admin -z ovn
  - name: Add the anyid field
    shell:  oc adm policy add-scc-to-user anyuid -z ovn
  - name: Save the token for later usage
    shell: oc sa get-token ovn
    register: ovn_key
  - local_action: copy content={{ ovn_key.stdout }} dest=/root/ovn.token
- hosts: master1
  become: yes
  become_user: root
  tasks:
  - name: Get the /etc/origin/master/ca.crt
    fetch:
          src: /etc/origin/master/ca.crt
          dest: /root/
          flat: yes
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: Create the master directory 
    file: path=/etc/origin/master state=directory
  - name: Place Crt 
    copy:
       src: /root/ca.crt
       dest: /etc/origin/master
       mode: u+rw
  - name: Remove old network setup
    shell: cd /etc/origin/node;sed -i.bak '/networkConfig:/,/nodeName:/{//!d}' node-config.yaml
  - name: Add new network setup
    blockinfile:
       dest: /etc/origin/node/node-config.yaml
       insertafter: "networkConfig:"
       create: no
       block: |
                 #
                    mtu: 1450
                    networkPluginName: cni
- hosts: nodes
  become: yes
  become_user: root
  vars:
     user: "{{lookup('env','USER')}}"
     config_dir: "/etc/origin/master"
     apihost: "{{ lookup('file', '/root/api_host.txt') }}"
  tasks:
  - debug: msg="User is {{ user }}"
  - name: Copy token to all masters
    copy: 
       src: /root/ovn.token
       dest: "{{ config_dir }}/ovn.token"
  - name: Create systemd file for ovn-kubernetes node
    blockinfile:
      dest: /etc/systemd/system/ovn-kubernetes-node.service
      create: yes
      block: |
        [Unit]
        Description=Setup for ovn-kubernetes Node

        [Service]
        Type=simple
        ExecStart=/bin/bash /usr/local/bin/ovn-kubernetes-node.sh

        [Install]
        WantedBy=multi-user.target

  - name: Create systemd file for ovn-kubernetes master
    blockinfile:
      dest: /etc/systemd/system/ovn-kubernetes-master.service
      create: yes
      block: |
        [Unit]
        Description=Setup for ovn-kubernetes master

        [Service]
        Type=simple
        ExecStart=/bin/bash /usr/local/bin/ovn-kubernetes-master.sh

        [Install]
        WantedBy=multi-user.target
        #WantedBy=openshift-master.service
        #WantedBy=ovn-kubernetes-master-setup.service

  - name: Clear any previous ovn-kubernetes-master.sh
    file: path=/usr/local/bin/ovn-kubernetes-master.sh state=absent
  - name: Create ovn-kubernetes-master.sh 
    blockinfile:
      dest: /usr/local/bin/ovn-kubernetes-master.sh
      create: yes
      mode: u+rwx
      block: |

         set -o errexit
         set -o nounset
         set -o pipefail

         function ovn-kubernetes-master() {
            local config_dir=$1
            token=$(cat ${config_dir}/ovn.token)

            local master_config="${config_dir}/master-config.yaml"
            cluster_cidr="10.128.0.0/14"
            apiserver="{{lookup('file', '/root/api_host.txt')}}" 

            echo "Enabling and start ovn-kubernetes master services"
            /usr/bin/ovnkube \
                 --k8s-apiserver "${apiserver}" \
                 --k8s-cacert "${config_dir}/ca.crt" \
                 --k8s-token "${token}" \
                 --cluster-subnet "${cluster_cidr}" \
                 --nb-address "tcp://{{lookup('dig','master1')}}:6641" \
                  -sb-address "tcp://{{lookup('dig','master1')}}:6642" \
                  --init-master `hostname` \
                  --service-cluster-ip-range=172.30.0.0/16 \
                  --net-controller
         }
         ovn-kubernetes-master "{{ config_dir }}"
  - name: Create ovn-kubernetes-node.sh 
    blockinfile:
      dest: /usr/local/bin/ovn-kubernetes-node.sh
      create: yes
      mode: u+rwx
      block: |

         set -o errexit
         set -o nounset
         set -o pipefail

         function ovn-kubernetes-node() {
            local config_dir=$1
            token=$(cat ${config_dir}/ovn.token)

            apiserver="{{lookup('file', '/root/api_host.txt')}}" 
            cluster_cidr="10.128.0.0/14"

            echo "Enabling and start ovn-kubernetes node services"
            /usr/bin/ovnkube \
                 --k8s-apiserver "${apiserver}" \
                 --k8s-cacert "${config_dir}/ca.crt" \
                 --k8s-token "${token}" \
                 --cluster-subnet "${cluster_cidr}" \
                 --nb-address "tcp://{{lookup('dig','master1')}}:6641" \
                 --sb-address "tcp://{{lookup('dig','master1')}}:6642" \
                 --init-gateways \
                 --service-cluster-ip-range=172.30.0.0/16 \
                 --init-node `hostname` 
         }
         ovn-kubernetes-node "{{ config_dir }}"
  - name: Clear old config file
    file: path=/etc/openvswitch/ovn_k8s.conf state=absent
  - name: Create openvswitch /etc directory
    file: path=/etc/openvswitch state=directory
  - name: Create /etc/openvswitch/ovn_k8s.conf
    blockinfile:
      dest: /etc/openvswitch/ovn_k8s.conf
      create: yes
      block: |
         [logging]
         #loglevel=5
         #logfile=/var/log/ovnkube.log
         #https://gswmon.southcentralus.cloudapp.azure.com:8443
         [kubernetes]
         apiserver="{{lookup('file', '/root/api_host.txt')}}"  # kubernetes api server, or the load balanced address for the multiple api server case
         token="{{lookup('file', '/root/ovn.token')}}"
         cacert=/etc/origin/master/ca.crt

         [ovnnorth]
         address="tcp://{{lookup('dig','master1')}}:6641" # this master machine's IP address

         [ovnsouth]
         address="tcp://{{lookup('dig','master1')}}:6642"
  - name: open firewall 6641
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6641 -j ACCEPT
  - name: open firewall 6642
    shell: iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 6642 -j ACCEPT
  - name: open firewall 6081
    shell: iptables -A OS_FIREWALL_ALLOW -p udp -m state --state NEW -m udp --dport 6081 -j ACCEPT
  - name: Save iptables rules
    shell: service iptables save
  - name: enable ovsdb-server
    service:
        name: ovsdb-server
        state: started
        enabled: yes
  - name: enable ovn-northd
    service:
        name: ovn-northd
        state: started
        enabled: yes
  - name: Start openvswitch
    service:
        name: openvswitch
        state: started
        enabled: yes
  - name: Start ovn-controller
    service:
        name: ovn-controller
        state: started
        enabled: yes
  - name: enable ovn-kubernetes-master.service
    service:
        name: ovn-kubernetes-master.service
        state: stopped
        enabled: no
  - name: enable ovn-kubernetes-node.service
    service:
        name: ovn-kubernetes-node.service
        state: stopped
        enabled: no
- hosts: masters
  become: yes
  become_user: root
  tasks:
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
  - name: Remove old network setup
    shell: cd /etc/origin/master;sed -i.bak '/networkConfig:/,/oauthConfig:/{//!d}' master-config.yaml
  - name: Add new network setup
    blockinfile:
       dest: /etc/origin/master/master-config.yaml
       insertafter: "networkConfig:"
       create: no
       block: |
                 #
                   clusterNetworkCIDR: 10.128.0.0/14
                   clusterNetworks:
                   - cidr: 10.128.0.0/14
                     hostSubnetLength: 9
                   externalIPNetworkCIDRs: null
                   hostSubnetLength: 9
                   ingressIPNetworkCIDR: 172.29.0.0/16
                   networkPluginName: cni
                   serviceNetworkCIDR: 172.30.0.0/16
  - name: restart atomic-openshift-master-controllers
    shell: systemctl restart atomic-openshift-master-controllers
  - name: restart atomic-openshift-master-api
    shell: systemctl restart atomic-openshift-master-api
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: restart atomic-openshift-node
    shell: systemctl restart  atomic-openshift-node
- hosts: node01
  tasks:
  - name: Grab /etc/openvswitch/ovn_k8s.conf
    fetch: 
      src:  /etc/openvswitch/ovn_k8s.conf
      dest: /tmp/ovn_k8s.conf
      flat: yes
- hosts: nodes:!master1
  become: yes
  become_user: root
  tasks:
  - name: enable ovn-kubernetes-node.service
    service:
        name: ovn-kubernetes-node.service
        state: started
        enabled: yes
  - name: Start ovn-kubernetes-node
    shell: systemctl start ovn-kubernetes-node
- hosts: master1
  become: yes
  become_user: root
  tasks:
  - name: enable ovn-kubernetes-master.service
    service:
        name: ovn-kubernetes-master.service
        state: started
        enabled: yes
  - name: enable ovn-kubernetes-node.service
    service:
        name: ovn-kubernetes-node.service
        state: started
        enabled: yes
  - name: Start ovn-kubernetes-master
    shell: systemctl start ovn-kubernetes-master
  - name: Start ovn-kubernetes-node
    shell: systemctl start ovn-kubernetes-node
