- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Get server url
    shell: "oc whoami --show-server"
    register: api_url
  - local_action: copy content={{lookup('dig',api_url.stdout.rpartition('//')[2].split(':')[0])}} dest=/root/api_host.txt
  - name: Install go
    yum:
      name: golang
      enablerepo: rhel-7-server-optional-rpms
  - name: Clear previous build if it exists
    file: path=~/ovn-kubernetes state=absent
  - name: Clone to ovn-kubernetes repo
    shell: git clone https://github.com/openvswitch/ovn-kubernetes ~/ovn-kubernetes
  - name: Create destination directory
    file: path=/opt/cni/bin state=directory
  - name: Create the ovn-kubernetes directory
    file: path=~/ovn-kubernetes state=directory
  - name: Build The Controller (Linux)
    shell: cd ~/ovn-kubernetes;cd go-controller;make;make install
  - name: Build The Controller (Windows)
    shell: cd ~/ovn-kubernetes;cd go-controller;make clean;make windows
  - name: Create directory for cni plugins
    file: path=/tmp/cniplugin state=directory
  - name: Get cni plugins
    shell: wget -q https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz; tar xvzf cni-plugins-amd64-v0.7.1.tgz -C /tmp/cniplugin
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: Create the master directory 
    file: path=/etc/origin/master state=directory
  - name: Create /opt/cni/bin
    file: path=/opt/cni/bin state=directory
  - name: Create openvswitch /etc directory
    file: path=/etc/openvswitch state=directory
  - name: Push the ovn-k8s-cni-overlay to all nodes
    copy:
      src: /opt/cni/bin/ovn-k8s-cni-overlay
      dest: /opt/cni/bin/ovn-k8s-cni-overlay
      mode: u+rwx
  - name: Push the ovnkube to all nodes
    copy:
      src: /usr/bin/ovnkube
      dest: /usr/bin/ovnkube
      mode: u+rwx
  - name: Push the cni loopback plugin to all nodes
    copy:
      src: /tmp/cniplugin/loopback
      dest: /opt/cni/bin/loopback
      mode: u+rwx
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
  - name: Remove old network setup
    shell: cd /etc/origin/node;sed -i.bak '/networkConfig:/,/nodeName:/{//!d}' node-config.yaml
  - name: Add new network setup
    blockinfile:
       dest: /etc/origin/node/node-config.yaml
       insertafter: "networkConfig:"
       create: no
       block: |
                 #
                    mtu: 1450
                    networkPluginName: cni
- hosts: nodes
  become: yes
  become_user: root
  vars:
     user: "{{lookup('env','USER')}}"
     config_dir: "/etc/origin/master"
  tasks:
  - debug: msg="User is {{ user }}"

  - name: Remove atomic-openshift-sdn-ovs
    yum:
      name=atomic-openshift-sdn-ovs
      state=absent
  - name: Remove openvswitch
    yum:
      name=openvswitch
      state=absent
  - name: Copy token to all masters
    copy: 
       src: /root/ovn.token
       dest: "{{ config_dir }}/ovn.token"
  - name: Create systemd file for ovn-kubernetes master
    blockinfile:
      dest: /etc/systemd/system/ovn-kubernetes-master.service
      create: yes
      block: |
        [Unit]
        Description=Setup for ovn-kubernetes master
        #Requires=openshift-master.service
        #After=openshift-master.service
        #After=ovn-kubernetes-master-setup.service

        [Service]
        Type=simple
        ExecStart=/bin/bash /usr/local/bin/ovn-kubernetes-master.sh

        [Install]
        WantedBy=multi-user.target
        #WantedBy=openshift-master.service
        #WantedBy=ovn-kubernetes-master-setup.service

  - name: install upstream openvswitch 2.7
    shell: rpm --replacepkgs -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-2.7.0-1.el7.x86_64.rpm
  - name: Install ovn common
    shell: rpm -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-ovn-common-2.7.0-1.el7.x86_64.rpm
  - name: install ovn central
    shell: rpm -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-ovn-central-2.7.0-1.el7.x86_64.rpm
  - name: Install ovn host
    shell: rpm -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-ovn-host-2.7.0-1.el7.x86_64.rpm
  - name: Install python-openvswitch
    shell: yum -y install python-openvswitch
  - name: Install ovn docker
    shell: rpm -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-ovn-docker-2.7.0-1.el7.x86_64.rpm
  - name: Install ovn vtep
    shell: rpm -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-ovn-vtep-2.7.0-1.el7.x86_64.rpm
  - name: Install ovn devel
    shell: rpm --replacepkgs -i http://cbs.centos.org/kojifiles/packages/openvswitch/2.7.0/1.el7/x86_64/openvswitch-devel-2.7.0-1.el7.x86_64.rpm
  - name: Clear any previous ovn-kubernetes-master.sh
    file: path=/usr/local/bin/ovn-kubernetes-master.sh state=absent
  - name: Create ovn-kubernetes-master.sh 
    blockinfile:
      dest: /usr/local/bin/ovn-kubernetes-master.sh
      create: yes
      block: |

         set -o errexit
         set -o nounset
         set -o pipefail

         function ovn-kubernetes-master() {
            local config_dir=$1
            local kube_config="${config_dir}/admin.kubeconfig"

            token=$(cat ${config_dir}/ovn.token)

            local master_config="${config_dir}/master-config.yaml"
            cluster_cidr=$(python -c "import yaml; stream = file('${master_config}', 'r'); y = yaml.load(stream); print y['networkConfig']['clusterNetworks'][0]['cidr']")
            apiserver=$(oc --config="${kube_config}" config view -o custom-columns=server:clusters[0].cluster.server | grep http)
            ovn_master_host=$(echo -n ${apiserver} | cut -d "/" -f 3 | cut -d ":" -f 1)
            ovn_master_ip=$(dig +short $ovn_master_host)

            echo "Enabling and start ovn-kubernetes master services"
            /usr/bin/ovnkube \
                 --k8s-apiserver "${apiserver}" \
                 --k8s-cacert "${config_dir}/ca.crt" \
                 --k8s-token "${token}" \
                 --cluster-subnet "${cluster_cidr}" \
                 --nb-address "tcp://{{lookup('dig','master1')}}:6641" \
                  -sb-address "tcp://{{lookup('dig','master1')}}:6642" \
                  --init-master `hostname` \
                  --net-controller
         }
         ovn-kubernetes-master "{{ config_dir }}"
  - name: Clear old config file
    file: path=/etc/openvswitch/ovn_k8s.conf state=absent
  - name: Create /etc/openvswitch/ovn_k8s.conf
    blockinfile:
      dest: /etc/openvswitch/ovn_k8s.conf
      create: yes
      block: |
         [logging]
         #loglevel=5
         #logfile=/var/log/ovnkube.log
         #https://gswmon.southcentralus.cloudapp.azure.com:8443
         [kubernetes]
         apiserver="https://{{lookup('file', '/root/api_host.txt')}}:8443"  # kubernetes api server, or the load balanced address for the multiple api server case
         token="{{lookup('file', '/root/ovn.token')}}"
         cacert=/etc/origin/master/ca.crt

         [ovnnorth]
         address="tcp://{{lookup('dig','master1')}}:6641" # this master machine's IP address

         [ovnsouth]
         address="tcp://{{lookup('dig','master1')}}:6642"
  - name: open firewall 6641
    shell: iptables -A INPUT -p tcp --dport 6641 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT; iptables -A OUTPUT -p tcp --sport 6641 -m conntrack --ctstate ESTABLISHED -j ACCEPT
  - name: open firewall 6642
    shell: iptables -A INPUT -p tcp --dport 6642 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT; iptables -A OUTPUT -p tcp --sport 6642 -m conntrack --ctstate ESTABLISHED -j ACCEPT
  - name: open firewall 6081
    shell: iptables -A INPUT -p udp --dport 6081 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT; iptables -A OUTPUT -p udp --sport 6081 -m conntrack --ctstate ESTABLISHED -j ACCEPT
  - name: Save iptables rules
    shell: service iptables save
  - name: enable ovsdb-server
    service:
        name: ovsdb-server
        state: started
        enabled: yes
  - name: enable ovn-northd
    service:
        name: ovn-northd
        state: started
        enabled: yes
  - name: Start openvswitch
    service:
        name: openvswitch
        state: started
        enabled: yes
  - name: enable ovn-kubernetes-master.service
    service:
        name: ovn-kubernetes-master.service
        state: started
        enabled: yes
- hosts: masters
  become: yes
  become_user: root
  tasks:
  - name: Create destination directory
    file: path=/etc/cni/net.d state=directory
  - name: Create cni config
    copy:
      dest: /etc/cni/net.d/10-ovn-kubernetes.conf
      content: |
               {"name":"ovn-kubernetes", "type":"ovn-k8s-cni-overlay"}
  - name: Remove old network setup
    shell: cd /etc/origin/master;sed -i.bak '/networkConfig:/,/oauthConfig:/{//!d}' master-config.yaml
  - name: Add new network setup
    blockinfile:
       dest: /etc/origin/master/master-config.yaml
       insertafter: "networkConfig:"
       create: no
       block: |
                 #
                   clusterNetworkCIDR: 10.128.0.0/14
                   clusterNetworks:
                   - cidr: 10.128.0.0/14
                     hostSubnetLength: 9
                   externalIPNetworkCIDRs: null
                   hostSubnetLength: 9
                   ingressIPNetworkCIDR: 172.29.0.0/16
                   networkPluginName: cni
                   serviceNetworkCIDR: 172.30.0.0/16
  - name: restart atomic-openshift-master-controllers
    service:
        name: atomic-openshift-master-controllers
        state: restarted
  - name: restart atomic-openshift-master-api
    service:
        name: atomic-openshift-master-api
        state: restarted
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: restart atomic-openshift-node
    service:
        name: atomic-openshift-node
        state: restarted
- hosts: node01
  tasks:
  - name: Grab /etc/openvswitch/ovn_k8s.conf
    fetch: 
      src:  /etc/openvswitch/ovn_k8s.conf
      dest: /tmp/ovn_k8s.conf
      flat: yes
- hosts: windows
  gather_facts: no
  tasks:
  - name: Copy ovn_k8s.conf to windows nodes
    win_copy:
       src: /tmp/ovn_k8s.conf
       dest: C:\Program Files\Cloudbase Solutions\Open vSwitch\conf\ovn_k8s.conf
       force: yes
  - name: copy ovn-k8s-cni-overlay.exe
    win_copy:
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
       dest: /bin/ovn-k8s-cni-overlay.exe
       force: yes
  - name: copy ovn ovnkube.exe
    win_copy:
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
       dest: /bin/ovnkube.exe
       force: yes


