- hosts: windows
  gather_facts: no
  serial: 1
  tasks:
  - name: Expand System Disk
    win_shell: expanddisk.ps1
    args:
      chdir: c:\k\hybrid\bin
  - name: Prepare to create docker network
    win_scheduled_task:
      name: docker-create
      description: Create The Docker Network
      executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive c:\k\hybrid\bin\docker-create.ps1
      frequency: once
      enabled:   true
      time:      "14:00:00"
      user:      SYSTEM
  - name: Execute the creation of the docker network
    win_shell: Start-ScheduledTask -TaskName docker-create
  - name: Pause for Docker Setup
    pause:
       minutes: 1
  - name: Prepare to setup the windows sdn setup
    win_scheduled_task:
      name: setup-network
      description: Create The Docker Network
      executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Unrestricted -NonInteractive c:\k\hybrid\bin\setup-network.ps1
      frequency: once
      enabled:   true
      time:      "14:00:00"
      user:      SYSTEM
  - name: Execute the setup of the windows sdn
    win_shell: Start-ScheduledTask -TaskName setup-network
  - name: Pause for sdn setup
    pause:
       minutes: 1
