- hosts: winnode01
  gather_facts: no
  tasks:
  - name: Setup Kubeovn Service
    win_shell: setup_kubeovn_service.ps1
    args:
      chdir: \k\hybrid\bin
  - name: Setup Kubelet Service
    win_shell: setup_kubelet_service.ps1
    args:
      chdir: \k\hybrid\bin
  - name: Enable kubeovn
    win_shell: Set-Service kubeovn -StartupType Automatic
  - name: Start kubeovn
    win_shell: Start-Service kubeovn
  - name: Enable kubelet
    win_shell: Set-Service kubelet -StartupType Automatic
  - name: Start kubelet
    win_shell: Start-Service kubelet 
    



