- hosts: masters
  become: yes
  become_user: root
  tasks:
  - name: Remove old network setup
    shell: cd /etc/origin/master;sed -i.bak '/networkConfig:/,/oauthConfig:/{//!d}' master-config.yaml
  - name: Add new network setup
    blockinfile:
       dest: /etc/origin/master/master-config.yaml
       insertafter: "networkConfig:"
       create: no
       block: |
                 #
                   clusterNetworks:
                   - cidr: 10.128.0.0/14
                     hostSubnetLength: 9
                   externalIPNetworkCIDRs: null
                   ingressIPNetworkCIDR: 172.29.0.0/16
                   networkPluginName: ovn-k8s-cni-overlay
                   serviceNetworkCIDR: 172.30.0.0/16


