- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  tasks:
  - name: copy ovn-k8s-cni-overlay.exe
    copy: 
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
       dest: /bin/ovn-k8s-cni-overlay.exe
       force: yes
  - name: copy ovn ovnkube.exe
    copy: 
       src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
       dest: /bin/ovnkube.exe
       force: yes
