- hosts: localhost
  become: yes
  become_user: root
  vars: 
    api_url: "https://gswmon.southcentralus.cloudapp.azure.com:8443"
  tasks:
  - debug:
      msg: urlparts="{{ api_url.rpartition('//')[2].split(':')[0] }}"
