- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Get cni plugins
    shell: wget https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz; tar xvzf cni-plugins-amd64-v0.7.1.tgz -C /tmp/cniplugin
- hosts: nodes
  become: yes
  become_user: root
  tasks:
  - name: Push the cni loopback plugin to all nodes
    copy:
      src: /tmp/cniplugin/loopback
      dest: /opt/cni/bin/loopback
      mode: u+rwx


