- hosts: windows
  gather_facts: no
  vars:
     user: "{{lookup('env','USER')}}"
  tasks:
  - name: Check Comm
    win_ping:
  - name: Install HyperV
    win_shell: Install-WindowsFeature -Name Hyper-V, RSAT-Hyper-V-Tools
  - name: Install the Nuget provider
    win_shell: Install-PackageProvider -Name NuGet -Force
  - name: Install Package Manager Provider
    win_shell: Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
  - name: Install Docker Provider
    win_shell: Install-Package -Name docker -ProviderName DockerMsftProvider -Confirm
  - name: Install Docker
    win_shell: Install-Package Docker -ProviderName DockerMsftProvider -Force
  - name: Windows Update
    win_shell: Install-Package PSWindowsUpdate -Force
  - name: Do updates
    win_shell: Get-WUInstall -AcceptAll 
  - name: Restart Windows Nodes
    win_reboot:
        reboot_timeout: 3600
  - name: Pull down windowsservercore 1803
    win_shell: docker pull microsoft/windowsservercore:1803
  - name: Tag The image
    win_shell: docker tag microsoft/windowsservercore:1803 microsoft/windowsservercore:latest
